<?php
/**
 * HttpClientConnectionAttributes
 *
 * PHP version 5
 *
 * @category Class
 * @package  NexusClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace NexusClient\Model;

use \ArrayAccess;
use \NexusClient\ObjectSerializer;

/**
 * HttpClientConnectionAttributes Class Doc Comment
 *
 * @category Class
 * @package  NexusClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HttpClientConnectionAttributes implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'HttpClientConnectionAttributes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'retries' => 'int',
        'user_agent_suffix' => 'string',
        'timeout' => 'int',
        'enable_circular_redirects' => 'bool',
        'enable_cookies' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'retries' => 'int32',
        'user_agent_suffix' => null,
        'timeout' => 'int32',
        'enable_circular_redirects' => null,
        'enable_cookies' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'retries' => 'retries',
        'user_agent_suffix' => 'userAgentSuffix',
        'timeout' => 'timeout',
        'enable_circular_redirects' => 'enableCircularRedirects',
        'enable_cookies' => 'enableCookies'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'retries' => 'setRetries',
        'user_agent_suffix' => 'setUserAgentSuffix',
        'timeout' => 'setTimeout',
        'enable_circular_redirects' => 'setEnableCircularRedirects',
        'enable_cookies' => 'setEnableCookies'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'retries' => 'getRetries',
        'user_agent_suffix' => 'getUserAgentSuffix',
        'timeout' => 'getTimeout',
        'enable_circular_redirects' => 'getEnableCircularRedirects',
        'enable_cookies' => 'getEnableCookies'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['retries'] = isset($data['retries']) ? $data['retries'] : null;
        $this->container['user_agent_suffix'] = isset($data['user_agent_suffix']) ? $data['user_agent_suffix'] : null;
        $this->container['timeout'] = isset($data['timeout']) ? $data['timeout'] : null;
        $this->container['enable_circular_redirects'] = isset($data['enable_circular_redirects']) ? $data['enable_circular_redirects'] : null;
        $this->container['enable_cookies'] = isset($data['enable_cookies']) ? $data['enable_cookies'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['retries']) && ($this->container['retries'] > 10)) {
            $invalidProperties[] = "invalid value for 'retries', must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['retries']) && ($this->container['retries'] < 0)) {
            $invalidProperties[] = "invalid value for 'retries', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['timeout']) && ($this->container['timeout'] > 3600)) {
            $invalidProperties[] = "invalid value for 'timeout', must be smaller than or equal to 3600.";
        }

        if (!is_null($this->container['timeout']) && ($this->container['timeout'] < 1)) {
            $invalidProperties[] = "invalid value for 'timeout', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets retries
     *
     * @return int
     */
    public function getRetries()
    {
        return $this->container['retries'];
    }

    /**
     * Sets retries
     *
     * @param int $retries Total retries if the initial connection attempt suffers a timeout
     *
     * @return $this
     */
    public function setRetries($retries)
    {

        if (!is_null($retries) && ($retries > 10)) {
            throw new \InvalidArgumentException('invalid value for $retries when calling HttpClientConnectionAttributes., must be smaller than or equal to 10.');
        }
        if (!is_null($retries) && ($retries < 0)) {
            throw new \InvalidArgumentException('invalid value for $retries when calling HttpClientConnectionAttributes., must be bigger than or equal to 0.');
        }

        $this->container['retries'] = $retries;

        return $this;
    }

    /**
     * Gets user_agent_suffix
     *
     * @return string
     */
    public function getUserAgentSuffix()
    {
        return $this->container['user_agent_suffix'];
    }

    /**
     * Sets user_agent_suffix
     *
     * @param string $user_agent_suffix Custom fragment to append to User-Agent header in HTTP requests
     *
     * @return $this
     */
    public function setUserAgentSuffix($user_agent_suffix)
    {
        $this->container['user_agent_suffix'] = $user_agent_suffix;

        return $this;
    }

    /**
     * Gets timeout
     *
     * @return int
     */
    public function getTimeout()
    {
        return $this->container['timeout'];
    }

    /**
     * Sets timeout
     *
     * @param int $timeout Seconds to wait for activity before stopping and retrying the connection
     *
     * @return $this
     */
    public function setTimeout($timeout)
    {

        if (!is_null($timeout) && ($timeout > 3600)) {
            throw new \InvalidArgumentException('invalid value for $timeout when calling HttpClientConnectionAttributes., must be smaller than or equal to 3600.');
        }
        if (!is_null($timeout) && ($timeout < 1)) {
            throw new \InvalidArgumentException('invalid value for $timeout when calling HttpClientConnectionAttributes., must be bigger than or equal to 1.');
        }

        $this->container['timeout'] = $timeout;

        return $this;
    }

    /**
     * Gets enable_circular_redirects
     *
     * @return bool
     */
    public function getEnableCircularRedirects()
    {
        return $this->container['enable_circular_redirects'];
    }

    /**
     * Sets enable_circular_redirects
     *
     * @param bool $enable_circular_redirects Whether to enable redirects to the same location (may be required by some servers)
     *
     * @return $this
     */
    public function setEnableCircularRedirects($enable_circular_redirects)
    {
        $this->container['enable_circular_redirects'] = $enable_circular_redirects;

        return $this;
    }

    /**
     * Gets enable_cookies
     *
     * @return bool
     */
    public function getEnableCookies()
    {
        return $this->container['enable_cookies'];
    }

    /**
     * Sets enable_cookies
     *
     * @param bool $enable_cookies Whether to allow cookies to be stored and used
     *
     * @return $this
     */
    public function setEnableCookies($enable_cookies)
    {
        $this->container['enable_cookies'] = $enable_cookies;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


