<?php
/**
 * ApiCertificateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  NexusClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace NexusClient;

/**
 * ApiCertificateTest Class Doc Comment
 *
 * @category    Class
 * @description ApiCertificate
 * @package     NexusClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApiCertificateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApiCertificate"
     */
    public function testApiCertificate()
    {
    }

    /**
     * Test attribute "expires_on"
     */
    public function testPropertyExpiresOn()
    {
    }

    /**
     * Test attribute "fingerprint"
     */
    public function testPropertyFingerprint()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "issued_on"
     */
    public function testPropertyIssuedOn()
    {
    }

    /**
     * Test attribute "issuer_common_name"
     */
    public function testPropertyIssuerCommonName()
    {
    }

    /**
     * Test attribute "issuer_organization"
     */
    public function testPropertyIssuerOrganization()
    {
    }

    /**
     * Test attribute "issuer_organizational_unit"
     */
    public function testPropertyIssuerOrganizationalUnit()
    {
    }

    /**
     * Test attribute "pem"
     */
    public function testPropertyPem()
    {
    }

    /**
     * Test attribute "serial_number"
     */
    public function testPropertySerialNumber()
    {
    }

    /**
     * Test attribute "subject_common_name"
     */
    public function testPropertySubjectCommonName()
    {
    }

    /**
     * Test attribute "subject_organization"
     */
    public function testPropertySubjectOrganization()
    {
    }

    /**
     * Test attribute "subject_organizational_unit"
     */
    public function testPropertySubjectOrganizationalUnit()
    {
    }
}
