<?php
/**
 * DockerAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  NexusClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace NexusClient;

/**
 * DockerAttributesTest Class Doc Comment
 *
 * @category    Class
 * @description DockerAttributes
 * @package     NexusClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DockerAttributesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DockerAttributes"
     */
    public function testDockerAttributes()
    {
    }

    /**
     * Test attribute "v1_enabled"
     */
    public function testPropertyV1Enabled()
    {
    }

    /**
     * Test attribute "force_basic_auth"
     */
    public function testPropertyForceBasicAuth()
    {
    }

    /**
     * Test attribute "http_port"
     */
    public function testPropertyHttpPort()
    {
    }

    /**
     * Test attribute "https_port"
     */
    public function testPropertyHttpsPort()
    {
    }
}
