<?php
/**
 * HostedStorageAttributesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HostedStorageAttributesTest Class Doc Comment
 *
 * @category    Class
 * @description HostedStorageAttributes
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HostedStorageAttributesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HostedStorageAttributes"
     */
    public function testHostedStorageAttributes()
    {
    }

    /**
     * Test attribute "blob_store_name"
     */
    public function testPropertyBlobStoreName()
    {
    }

    /**
     * Test attribute "strict_content_type_validation"
     */
    public function testPropertyStrictContentTypeValidation()
    {
    }

    /**
     * Test attribute "write_policy"
     */
    public function testPropertyWritePolicy()
    {
    }
}
