<?php
/**
 * RequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  NexusClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace NexusClient;

/**
 * RequestTest Class Doc Comment
 *
 * @category    Class
 * @description Request
 * @package     NexusClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Request"
     */
    public function testRequest()
    {
    }

    /**
     * Test attribute "system_information"
     */
    public function testPropertySystemInformation()
    {
    }

    /**
     * Test attribute "thread_dump"
     */
    public function testPropertyThreadDump()
    {
    }

    /**
     * Test attribute "metrics"
     */
    public function testPropertyMetrics()
    {
    }

    /**
     * Test attribute "configuration"
     */
    public function testPropertyConfiguration()
    {
    }

    /**
     * Test attribute "security"
     */
    public function testPropertySecurity()
    {
    }

    /**
     * Test attribute "log"
     */
    public function testPropertyLog()
    {
    }

    /**
     * Test attribute "task_log"
     */
    public function testPropertyTaskLog()
    {
    }

    /**
     * Test attribute "audit_log"
     */
    public function testPropertyAuditLog()
    {
    }

    /**
     * Test attribute "jmx"
     */
    public function testPropertyJmx()
    {
    }

    /**
     * Test attribute "limit_file_sizes"
     */
    public function testPropertyLimitFileSizes()
    {
    }

    /**
     * Test attribute "limit_zip_size"
     */
    public function testPropertyLimitZipSize()
    {
    }
}
