<?php
/**
 * UpdateLdapServerXoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * UpdateLdapServerXoTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateLdapServerXo
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateLdapServerXoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateLdapServerXo"
     */
    public function testUpdateLdapServerXo()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "protocol"
     */
    public function testPropertyProtocol()
    {
    }

    /**
     * Test attribute "use_trust_store"
     */
    public function testPropertyUseTrustStore()
    {
    }

    /**
     * Test attribute "host"
     */
    public function testPropertyHost()
    {
    }

    /**
     * Test attribute "port"
     */
    public function testPropertyPort()
    {
    }

    /**
     * Test attribute "search_base"
     */
    public function testPropertySearchBase()
    {
    }

    /**
     * Test attribute "auth_scheme"
     */
    public function testPropertyAuthScheme()
    {
    }

    /**
     * Test attribute "auth_realm"
     */
    public function testPropertyAuthRealm()
    {
    }

    /**
     * Test attribute "auth_username"
     */
    public function testPropertyAuthUsername()
    {
    }

    /**
     * Test attribute "connection_timeout_seconds"
     */
    public function testPropertyConnectionTimeoutSeconds()
    {
    }

    /**
     * Test attribute "connection_retry_delay_seconds"
     */
    public function testPropertyConnectionRetryDelaySeconds()
    {
    }

    /**
     * Test attribute "max_incidents_count"
     */
    public function testPropertyMaxIncidentsCount()
    {
    }

    /**
     * Test attribute "user_base_dn"
     */
    public function testPropertyUserBaseDn()
    {
    }

    /**
     * Test attribute "user_subtree"
     */
    public function testPropertyUserSubtree()
    {
    }

    /**
     * Test attribute "user_object_class"
     */
    public function testPropertyUserObjectClass()
    {
    }

    /**
     * Test attribute "user_ldap_filter"
     */
    public function testPropertyUserLdapFilter()
    {
    }

    /**
     * Test attribute "user_id_attribute"
     */
    public function testPropertyUserIdAttribute()
    {
    }

    /**
     * Test attribute "user_real_name_attribute"
     */
    public function testPropertyUserRealNameAttribute()
    {
    }

    /**
     * Test attribute "user_email_address_attribute"
     */
    public function testPropertyUserEmailAddressAttribute()
    {
    }

    /**
     * Test attribute "user_password_attribute"
     */
    public function testPropertyUserPasswordAttribute()
    {
    }

    /**
     * Test attribute "ldap_groups_as_roles"
     */
    public function testPropertyLdapGroupsAsRoles()
    {
    }

    /**
     * Test attribute "group_type"
     */
    public function testPropertyGroupType()
    {
    }

    /**
     * Test attribute "group_base_dn"
     */
    public function testPropertyGroupBaseDn()
    {
    }

    /**
     * Test attribute "group_subtree"
     */
    public function testPropertyGroupSubtree()
    {
    }

    /**
     * Test attribute "group_object_class"
     */
    public function testPropertyGroupObjectClass()
    {
    }

    /**
     * Test attribute "group_id_attribute"
     */
    public function testPropertyGroupIdAttribute()
    {
    }

    /**
     * Test attribute "group_member_attribute"
     */
    public function testPropertyGroupMemberAttribute()
    {
    }

    /**
     * Test attribute "group_member_format"
     */
    public function testPropertyGroupMemberFormat()
    {
    }

    /**
     * Test attribute "user_member_of_attribute"
     */
    public function testPropertyUserMemberOfAttribute()
    {
    }

    /**
     * Test attribute "auth_password"
     */
    public function testPropertyAuthPassword()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }
}
