<?php
/**
 * BlobStoreApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * BlobStoreApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BlobStoreApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createBlobStore
     *
     * Create an S3 blob store.
     *
     */
    public function testCreateBlobStore()
    {
    }

    /**
     * Test case for createFileBlobStore
     *
     * Create a file blob store.
     *
     */
    public function testCreateFileBlobStore()
    {
    }

    /**
     * Test case for deleteBlobStore
     *
     * Delete a blob store by name.
     *
     */
    public function testDeleteBlobStore()
    {
    }

    /**
     * Test case for getBlobStore
     *
     * Fetch a S3 blob store configuration.
     *
     */
    public function testGetBlobStore()
    {
    }

    /**
     * Test case for getFileBlobStoreConfiguration
     *
     * Get a file blob store configuration by name.
     *
     */
    public function testGetFileBlobStoreConfiguration()
    {
    }

    /**
     * Test case for listBlobStores
     *
     * List the blob stores.
     *
     */
    public function testListBlobStores()
    {
    }

    /**
     * Test case for quotaStatus
     *
     * Get quota status for a given blob store.
     *
     */
    public function testQuotaStatus()
    {
    }

    /**
     * Test case for updateBlobStore
     *
     * Update an S3 blob store configuration.
     *
     */
    public function testUpdateBlobStore()
    {
    }

    /**
     * Test case for updateFileBlobStore
     *
     * Update a file blob store configuration by name.
     *
     */
    public function testUpdateFileBlobStore()
    {
    }
}
