<?php
/**
 * RoutingRulesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * RoutingRulesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoutingRulesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createRoutingRule
     *
     * Create a single routing rule.
     *
     */
    public function testCreateRoutingRule()
    {
    }

    /**
     * Test case for deleteRoutingRule
     *
     * Delete a single routing rule.
     *
     */
    public function testDeleteRoutingRule()
    {
    }

    /**
     * Test case for getRoutingRule
     *
     * Get a single routing rule.
     *
     */
    public function testGetRoutingRule()
    {
    }

    /**
     * Test case for getRoutingRules
     *
     * List routing rules.
     *
     */
    public function testGetRoutingRules()
    {
    }

    /**
     * Test case for updateRoutingRule
     *
     * Update a single routing rule.
     *
     */
    public function testUpdateRoutingRule()
    {
    }
}
