<?php
/**
 * ScriptApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.26.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ScriptApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScriptApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for add
     *
     * Add a new script.
     *
     */
    public function testAdd()
    {
    }

    /**
     * Test case for browse
     *
     * List all stored scripts.
     *
     */
    public function testBrowse()
    {
    }

    /**
     * Test case for delete1
     *
     * Delete stored script by name.
     *
     */
    public function testDelete1()
    {
    }

    /**
     * Test case for edit
     *
     * Update stored script by name.
     *
     */
    public function testEdit()
    {
    }

    /**
     * Test case for read1
     *
     * Read stored script by name.
     *
     */
    public function testRead1()
    {
    }

    /**
     * Test case for run1
     *
     * Run stored script by name.
     *
     */
    public function testRun1()
    {
    }
}
